'use strict';

const CareerPilotData = {

  jobRoles: [
    {
      id: 'sde', title: 'Software Development Engineer', shortTitle: 'SDE', icon: '⚡',
      description: 'Master CS fundamentals and problem-solving to crack top tech companies like Google, Amazon, Microsoft.',
      color: '#6c63ff', gradient: 'linear-gradient(135deg,#6c63ff,#3ecfcf)',
      duration: '12–18 months', difficulty: 'Advanced', tags: ['DSA','System Design','CS Core'],
      steps: [
        { id:1, title:'Master a Programming Language', duration:'4–6 weeks',
          description:'Pick C++, Java, or Python and master it completely. This is your primary tool for everything ahead.',
          topics:['Syntax & Data Types','Control Flow','Functions & Recursion','OOP Concepts','STL / Collections','Big-O Complexity'],
          resources:[
            {title:'C++ Full Course',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'Java for Beginners',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'Python Crash Course',url:'https://www.youtube.com/@programmingwithmosh',type:'youtube',channel:'Programming with Mosh'},
            {title:'GeeksforGeeks',url:'https://geeksforgeeks.org',type:'docs'},
          ]},
        { id:2, title:'Data Structures & Algorithms', duration:'3–5 months',
          description:'The backbone of SDE interviews. Study every major DS and algorithm pattern. Solve 300+ problems.',
          topics:['Arrays, Strings, Hashing','Linked Lists, Stacks, Queues','Binary Search & Sorting','Trees & BST','Graphs (BFS/DFS/Dijkstra)','Dynamic Programming','Greedy Algorithms'],
          resources:[
            {title:'A2Z DSA Course',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
            {title:'DSA Full Series',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'DSA Algorithms',url:'https://www.youtube.com/@abdul_bari',type:'youtube',channel:'Abdul Bari'},
            {title:'LeetCode',url:'https://leetcode.com',type:'practice'},
            {title:'GeeksforGeeks Practice',url:'https://practice.geeksforgeeks.org/',type:'practice'},
            {title:'Coding Ninjas Studio',url:'https://www.codingninjas.com/studio',type:'practice'},
            {title:'Striver A2Z Sheet',url:'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',type:'docs'},
          ]},
        { id:3, title:'Operating Systems', duration:'3–4 weeks',
          description:'Understand how OS works — processes, threads, scheduling, memory. Asked in almost every SDE interview.',
          topics:['Process vs Thread','CPU Scheduling','Memory Management & Paging','Virtual Memory','File Systems','Deadlocks & Semaphores'],
          resources:[
            {title:'OS Full Course',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
            {title:'OS Playlist',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
            {title:'OS Notes - GFG',url:'https://www.geeksforgeeks.org/operating-systems/',type:'docs'},
          ]},
        { id:4, title:'Database Management Systems', duration:'2–3 weeks',
          description:'SQL and database fundamentals are tested in almost every SDE interview round.',
          topics:['SQL DDL & DML','Joins, Aggregations','Normalization (1NF–3NF)','Indexing & Query Optimization','ACID Properties','Transactions'],
          resources:[
            {title:'DBMS Full Course',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
            {title:'SQL Tutorial',url:'https://www.youtube.com/@techTFQ',type:'youtube',channel:'techTFQ'},
            {title:'SQLZoo',url:'https://sqlzoo.net',type:'practice'},
          ]},
        { id:5, title:'Computer Networks', duration:'2–3 weeks',
          description:'Understand how internet communication works — required for distributed systems questions.',
          topics:['OSI & TCP/IP Model','HTTP/HTTPS & DNS','TCP vs UDP','Subnetting & IP','Socket Basics'],
          resources:[
            {title:'Computer Networks',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
            {title:'CN Series',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:6, title:'System Design', duration:'6–8 weeks',
          description:'Design large-scale distributed systems. Crucial for final interview rounds.',
          topics:['Scalability Principles','Load Balancing','Caching (Redis, CDN)','Database Sharding','Message Queues (Kafka)','Microservices Architecture','CAP Theorem'],
          resources:[
            {title:'System Design Playlist',url:'https://www.youtube.com/@gkcs',type:'youtube',channel:'Gaurav Sen'},
            {title:'System Design Series',url:'https://www.youtube.com/@codeKarle',type:'youtube',channel:'codeKarle'},
            {title:'System Design Primer',url:'https://github.com/donnemartin/system-design-primer',type:'docs'},
          ]},
        { id:7, title:'Interview Prep & Projects', duration:'Ongoing',
          description:'Practice on competitive platforms, build real projects, and ace behavioral interviews.',
          topics:['LeetCode Top 150','Mock Interviews','2–3 Full-Stack Projects','GitHub Portfolio','Resume Building','Behavioral Questions (STAR method)'],
          resources:[
            {title:'LeetCode',url:'https://leetcode.com',type:'practice'},
            {title:'Codeforces',url:'https://codeforces.com',type:'practice'},
            {title:'CodeChef',url:'https://www.codechef.com/',type:'practice'},
            {title:'AtCoder',url:'https://atcoder.jp/',type:'practice'},
            {title:'NeetCode Roadmap',url:'https://neetcode.io/roadmap',type:'docs'},
          ]},
      ]
    },
    {
      id: 'ase', title: 'Associate Software Engineer', shortTitle: 'ASE', icon: '🛠️',
      description: 'Start your software career with strong programming basics, version control, and collaborative development.',
      color: '#10b981', gradient: 'linear-gradient(135deg,#10b981,#3b82f6)',
      duration: '6–10 months', difficulty: 'Beginner', tags: ['Programming','Git','Teamwork'],
      steps: [
        { id:1, title:'Programming Fundamentals', duration:'4–6 weeks',
          description:'Start with Python or Java. Understand variables, loops, functions, and basic OOP.',
          topics:['Variables & Data Types','Loops & Conditionals','Functions','Basic OOP','Error Handling'],
          resources:[
            {title:'Python for Beginners',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'Java Tutorials',url:'https://www.youtube.com/@Telusko',type:'youtube',channel:'Telusko'},
            {title:'freeCodeCamp',url:'https://freecodecamp.org',type:'docs'},
          ]},
        { id:2, title:'Version Control with Git', duration:'1–2 weeks',
          description:'Git is essential for any developer. Learn branching, merging, and pull requests.',
          topics:['Git Basics (init, add, commit)','Branching & Merging','GitHub Pull Requests','Conflict Resolution','Git Workflows'],
          resources:[
            {title:'Git & GitHub Full Course',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'GitHub Guides',url:'https://guides.github.com/',type:'docs'},
          ]},
        { id:3, title:'Basic Data Structures', duration:'4–6 weeks',
          description:'Learn fundamental data structures to write efficient code.',
          topics:['Arrays & Strings','Linked Lists','Stacks & Queues','Hash Maps','Basic Sorting'],
          resources:[
            {title:'DSA for Beginners',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'HackerRank Practice',url:'https://hackerrank.com/domains/data-structures',type:'practice'},
            {title:'LeetCode Easy',url:'https://leetcode.com/problemset/all/?difficulty=EASY',type:'practice'},
            {title:'GeeksforGeeks Basic',url:'https://practice.geeksforgeeks.org/explore?page=1&difficulty[]=0',type:'practice'},
          ]},
        { id:4, title:'Agile & Team Collaboration', duration:'1–2 weeks',
          description:'Understand how software teams work using Agile/Scrum methodologies.',
          topics:['Agile Manifesto','Scrum Framework','Sprints & User Stories','Jira / Trello Basics','Code Review Best Practices'],
          resources:[
            {title:'Atlassian Agile Guide',url:'https://www.atlassian.com/agile',type:'docs'},
          ]},
        { id:5, title:'Build a Portfolio Project', duration:'3–4 weeks',
          description:'Create a simple but working project to showcase your skills.',
          topics:['Pick a Problem to Solve','Use GitHub','Write a README','Deploy the App','Create LinkedIn Profile'],
          resources:[
            {title:'Project Ideas',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'GitHub Pages',url:'https://pages.github.com/',type:'docs'},
          ]},
      ]
    },
    {
      id: 'frontend', title: 'Frontend Developer', shortTitle: 'Frontend Dev', icon: '🎨',
      description: 'Build stunning, interactive user interfaces using HTML, CSS, JavaScript, and React.',
      color: '#f59e0b', gradient: 'linear-gradient(135deg,#f59e0b,#ef4444)',
      duration: '8–12 months', difficulty: 'Intermediate', tags: ['HTML/CSS','JavaScript','React'],
      steps: [
        { id:1, title:'HTML & CSS Mastery', duration:'3–4 weeks',
          description:'The foundation of every web page. Learn semantic HTML and modern CSS including Flexbox and Grid.',
          topics:['Semantic HTML5','CSS Box Model','Flexbox & CSS Grid','Responsive Design','CSS Variables & Animations','Media Queries'],
          resources:[
            {title:'HTML & CSS Full Course',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'HTML CSS Tutorial',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'MDN Web Docs',url:'https://developer.mozilla.org',type:'docs'},
          ]},
        { id:2, title:'JavaScript Fundamentals', duration:'6–8 weeks',
          description:'The language of the web. Master JS from basics to advanced concepts.',
          topics:['ES6+ Features','DOM Manipulation','Events & Async (Promises, async/await)','Fetch API','LocalStorage','Error Handling'],
          resources:[
            {title:'JavaScript Full Course',url:'https://www.youtube.com/@Fireship',type:'youtube',channel:'Fireship'},
            {title:'JS Tutorial',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'JavaScript.info',url:'https://javascript.info',type:'docs'},
          ]},
        { id:3, title:'React.js', duration:'6–8 weeks',
          description:'The most popular frontend library. Build component-based UIs.',
          topics:['Components & JSX','Props & State','Hooks (useState, useEffect, useContext)','React Router','Forms & Validation','API Integration'],
          resources:[
            {title:'React Full Course',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'React Tutorial',url:'https://www.youtube.com/@NetNinja',type:'youtube',channel:'The Net Ninja'},
            {title:'React Docs (Official)',url:'https://react.dev',type:'docs'},
          ]},
        { id:4, title:'State Management', duration:'2–3 weeks',
          description:'Handle complex state in large applications using Redux or Zustand.',
          topics:['Context API deep dive','Redux Toolkit','Zustand','React Query (server state)'],
          resources:[
            {title:'Redux Toolkit Tutorial',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'Redux Docs',url:'https://redux-toolkit.js.org',type:'docs'},
          ]},
        { id:5, title:'TypeScript', duration:'2–4 weeks',
          description:'Type-safe JavaScript for building large-scale applications.',
          topics:['Types & Interfaces','Generics','Type Narrowing','Utility Types','TypeScript with React'],
          resources:[
            {title:'TypeScript Full Course',url:'https://www.youtube.com/@NetNinja',type:'youtube',channel:'The Net Ninja'},
            {title:'TypeScript Docs',url:'https://typescriptlang.org/docs/',type:'docs'},
          ]},
        { id:6, title:'Portfolio & Projects', duration:'1–2 months',
          description:'Build 3 impressive projects that showcase your frontend skills.',
          topics:['Personal Portfolio Site','E-commerce UI Clone','Real-time App','Deploy on Vercel / Netlify','GitHub Portfolio'],
          resources:[
            {title:'Frontend Mentor',url:'https://frontendmentor.io',type:'practice'},
            {title:'CSSBattle',url:'https://cssbattle.dev/',type:'practice'},
            {title:'CodePen',url:'https://codepen.io/',type:'practice'},
            {title:'Vercel Deploy',url:'https://vercel.com',type:'docs'},
          ]},
      ]
    },
    {
      id: 'backend-node', title: 'Backend Developer (Node.js)', shortTitle: 'Backend (Node)', icon: '🟢',
      description: 'Build scalable server-side applications using Node.js, Express, and databases.',
      color: '#22c55e', gradient: 'linear-gradient(135deg,#22c55e,#15803d)',
      duration: '8–12 months', difficulty: 'Intermediate', tags: ['Node.js','Express','MongoDB/SQL'],
      steps: [
        { id:1, title:'JavaScript & ES6+ Mastery', duration:'4–6 weeks',
          description:'Node.js is JavaScript on the server. Master modern JS first.',
          topics:['ES6+ Features','Promises & async/await','Modules (CommonJS & ESM)','Error Handling','Event Loop'],
          resources:[
            {title:'JS Full Course',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'JavaScript.info',url:'https://javascript.info',type:'docs'},
          ]},
        { id:2, title:'Node.js Core', duration:'2–3 weeks',
          description:'Understand the Node.js runtime, event loop, and built-in modules.',
          topics:['Node.js Modules (fs, path, http)','Event Loop & Non-blocking I/O','npm & package.json','Environment Variables','Streams & Buffers'],
          resources:[
            {title:'Node.js Full Course',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'Node.js Docs',url:'https://nodejs.org/docs',type:'docs'},
          ]},
        { id:3, title:'Express.js & REST APIs', duration:'4–6 weeks',
          description:'Build REST APIs using Express.js with proper routing, middleware, and error handling.',
          topics:['Express Setup & Routing','Middleware','REST API Design','Request Validation','Error Handling Middleware','CORS & Security Headers'],
          resources:[
            {title:'Express.js Tutorial',url:'https://www.youtube.com/@NetNinja',type:'youtube',channel:'The Net Ninja'},
            {title:'REST API Design',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
          ]},
        { id:4, title:'Databases (SQL & NoSQL)', duration:'4–6 weeks',
          description:'Work with MongoDB (Mongoose) and PostgreSQL/MySQL.',
          topics:['MongoDB & Mongoose','PostgreSQL / MySQL','CRUD Operations','Data Modeling','Aggregation & Complex Queries','Indexing'],
          resources:[
            {title:'MongoDB Crash Course',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'SQL Tutorial',url:'https://www.youtube.com/@techTFQ',type:'youtube',channel:'techTFQ'},
          ]},
        { id:5, title:'Authentication & Security', duration:'2–3 weeks',
          description:'Implement secure auth with JWT, OAuth, and best security practices.',
          topics:['JWT Authentication','OAuth2 (Google Login)','bcrypt Password Hashing','Role-Based Access Control','Rate Limiting','Helmet.js'],
          resources:[
            {title:'JWT Auth Tutorial',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'OWASP Top 10',url:'https://owasp.org/Top10/',type:'docs'},
          ]},
        { id:6, title:'Docker & Deployment', duration:'2–3 weeks',
          description:'Containerize your app and deploy it to the cloud.',
          topics:['Docker Basics','Dockerfile & docker-compose','Deploy to Railway / Render / AWS EC2','Process Management (PM2)'],
          resources:[
            {title:'Docker Tutorial',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
          ]},
      ]
    },
    {
      id: 'backend-python', title: 'Backend Developer (Python)', shortTitle: 'Backend (Python)', icon: '🐍',
      description: 'Build robust APIs and backend systems using Python with Django or FastAPI.',
      color: '#3b82f6', gradient: 'linear-gradient(135deg,#3b82f6,#8b5cf6)',
      duration: '8–12 months', difficulty: 'Intermediate', tags: ['Python','Django','FastAPI'],
      steps: [
        { id:1, title:'Python Fundamentals', duration:'4–6 weeks',
          description:'Master Python deeply — one of the most powerful and readable languages.',
          topics:['Python Syntax & Data Types','OOP in Python','List Comprehensions','Decorators & Generators','File I/O','Virtual Environments'],
          resources:[
            {title:'Python Full Course',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'Python Tutorial',url:'https://www.youtube.com/@sentdex',type:'youtube',channel:'sentdex'},
          ]},
        { id:2, title:'Django Framework', duration:'6–8 weeks',
          description:'Django is a batteries-included framework. Build full-featured web apps rapidly.',
          topics:['Django Setup & MVT Architecture','URL Routing & Views','Templates & Forms','Django ORM','Django REST Framework (DRF)','Django Admin'],
          resources:[
            {title:'Django Full Course',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
          ]},
        { id:3, title:'FastAPI (Modern APIs)', duration:'3–4 weeks',
          description:'FastAPI is blazing fast and modern for building APIs.',
          topics:['FastAPI Basics','Pydantic Models','Async Endpoints','Dependency Injection','OpenAPI Docs','Auth with FastAPI'],
          resources:[
            {title:'FastAPI Docs',url:'https://fastapi.tiangolo.com',type:'docs'},
          ]},
        { id:4, title:'Databases & ORM', duration:'3–4 weeks',
          description:'Work with PostgreSQL, MySQL, and MongoDB with Python.',
          topics:['PostgreSQL with psycopg2','SQLAlchemy ORM','MongoDB with PyMongo','Alembic Migrations'],
          resources:[
            {title:'SQLAlchemy Tutorial',url:'https://www.youtube.com/@TechWithTim',type:'youtube',channel:'Tech With Tim'},
          ]},
        { id:5, title:'Auth, Testing & Deployment', duration:'2–3 weeks',
          description:'Secure your API and deploy it professionally.',
          topics:['JWT & OAuth2','pytest for Testing','Docker Containerization','Deploy to Heroku / Railway / AWS','CI/CD with GitHub Actions'],
          resources:[
            {title:'Docker for Python',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
          ]},
      ]
    },
    {
      id: 'backend-java', title: 'Backend Developer (Java)', shortTitle: 'Backend (Java)', icon: '☕',
      description: 'Build enterprise-grade backend applications using Java, Spring Boot, and Microservices.',
      color: '#f97316', gradient: 'linear-gradient(135deg,#f97316,#dc2626)',
      duration: '10–14 months', difficulty: 'Intermediate–Advanced', tags: ['Java','Spring Boot','Microservices'],
      steps: [
        { id:1, title:'Core Java Mastery', duration:'6–8 weeks',
          description:'Java is an enterprise-first language. Master its core thoroughly.',
          topics:['Java Syntax & OOP','Collections Framework','Exception Handling','Multithreading & Concurrency','Java 8+ (Streams, Lambdas)','JVM Internals'],
          resources:[
            {title:'Java Full Course',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'Java Tutorials',url:'https://www.youtube.com/@Telusko',type:'youtube',channel:'Telusko'},
          ]},
        { id:2, title:'Spring Boot', duration:'6–8 weeks',
          description:'Spring Boot is the industry-standard Java framework for backend APIs.',
          topics:['Spring IoC & Dependency Injection','Spring MVC & REST','Spring Data JPA / Hibernate','Spring Security','Spring Boot Testing'],
          resources:[
            {title:'Spring Boot Tutorial',url:'https://www.youtube.com/@amigoscode',type:'youtube',channel:'Amigoscode'},
            {title:'Spring Guides',url:'https://spring.io/guides',type:'docs'},
          ]},
        { id:3, title:'Microservices Architecture', duration:'4–6 weeks',
          description:'Build distributed systems using the Microservices pattern.',
          topics:['Microservices Principles','Spring Cloud','API Gateway','Service Discovery (Eureka)','Message Queues (Kafka)','Circuit Breaker Pattern'],
          resources:[
            {title:'Microservices with Spring Boot',url:'https://www.youtube.com/@amigoscode',type:'youtube',channel:'Amigoscode'},
          ]},
        { id:4, title:'Docker, CI/CD & Cloud', duration:'3–4 weeks',
          description:'Deploy Java microservices using Docker, Kubernetes, and cloud.',
          topics:['Docker & docker-compose','Kubernetes Basics','Jenkins / GitHub Actions','AWS EC2 / ECS','Maven / Gradle'],
          resources:[
            {title:'Docker Tutorial',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
          ]},
      ]
    },
    {
      id: 'data-analyst', title: 'Data Analyst', shortTitle: 'Data Analyst', icon: '📊',
      description: 'Turn raw data into business insights using SQL, Python, and visualization tools.',
      color: '#0ea5e9', gradient: 'linear-gradient(135deg,#0ea5e9,#6366f1)',
      duration: '6–10 months', difficulty: 'Beginner–Intermediate', tags: ['SQL','Python','Data Viz'],
      steps: [
        { id:1, title:'Excel & Spreadsheet Skills', duration:'2–3 weeks',
          description:'Excel is heavily used in analytics. Master formulas, pivot tables, and charts.',
          topics:['VLOOKUP, INDEX/MATCH','Pivot Tables & Charts','Data Cleaning in Excel','Conditional Formatting','Power Query Basics'],
          resources:[
            {title:'Excel Full Course',url:'https://www.youtube.com/@freecodecamp',type:'youtube',channel:'freeCodeCamp'},
          ]},
        { id:2, title:'SQL for Data Analysis', duration:'4–6 weeks',
          description:'SQL is the #1 skill for data analysts. Master querying and complex joins.',
          topics:['SELECT, WHERE, ORDER BY','Aggregate Functions (GROUP BY)','Joins (INNER, LEFT, RIGHT)','Subqueries & CTEs','Window Functions'],
          resources:[
            {title:'SQL for Data Analysis',url:'https://www.youtube.com/@techTFQ',type:'youtube',channel:'techTFQ'},
            {title:'HackerRank SQL',url:'https://hackerrank.com/domains/sql',type:'practice'},
          ]},
        { id:3, title:'Python for Data Analysis', duration:'6–8 weeks',
          description:'Use Python with Pandas and NumPy to process and analyze large datasets.',
          topics:['Python Basics','NumPy Arrays','Pandas DataFrames','Data Cleaning & Preprocessing','Exploratory Data Analysis (EDA)','Merging & Groupby'],
          resources:[
            {title:'Pandas Tutorial',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Python Data Analysis',url:'https://www.youtube.com/@sentdex',type:'youtube',channel:'sentdex'},
          ]},
        { id:4, title:'Data Visualization', duration:'3–4 weeks',
          description:'Create compelling charts and dashboards to communicate insights.',
          topics:['Matplotlib & Seaborn','Plotly (Interactive Charts)','Tableau Basics','Power BI Basics','Dashboard Design Principles'],
          resources:[
            {title:'Tableau for Beginners',url:'https://www.youtube.com/@freecodecamp',type:'youtube',channel:'freeCodeCamp'},
          ]},
        { id:5, title:'Statistics & Projects', duration:'1–2 months',
          description:'Statistics for drawing accurate conclusions and real project portfolio.',
          topics:['Descriptive Statistics','Hypothesis Testing','Correlation & Regression','A/B Testing','Kaggle Datasets'],
          resources:[
            {title:'StatQuest',url:'https://www.youtube.com/@statquest',type:'youtube',channel:'StatQuest'},
            {title:'Kaggle Learn',url:'https://kaggle.com/learn',type:'practice'},
          ]},
      ]
    },
    {
      id: 'ai-engineer', title: 'AI Engineer', shortTitle: 'AI Engineer', icon: '🤖',
      description: 'Build and deploy intelligent AI systems using deep learning, NLP, and modern AI frameworks.',
      color: '#8b5cf6', gradient: 'linear-gradient(135deg,#8b5cf6,#ec4899)',
      duration: '14–20 months', difficulty: 'Advanced', tags: ['Deep Learning','NLP','MLOps'],
      steps: [
        { id:1, title:'Python & Scientific Computing', duration:'4–6 weeks',
          description:'AI development requires strong Python and numerical computing skills.',
          topics:['Python OOP & Functional','NumPy & SciPy','Matplotlib','Jupyter Notebooks'],
          resources:[
            {title:'Python for Data Science',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
        { id:2, title:'Mathematics for AI', duration:'6–8 weeks',
          description:'AI is built on math. Master linear algebra, calculus, and statistics.',
          topics:['Linear Algebra (Vectors, Matrices)','Calculus (Derivatives, Gradients)','Probability & Statistics','Information Theory Basics'],
          resources:[
            {title:'3Blue1Brown Linear Algebra',url:'https://www.youtube.com/@3blue1brown',type:'youtube',channel:'3Blue1Brown'},
            {title:'StatQuest',url:'https://www.youtube.com/@statquest',type:'youtube',channel:'StatQuest'},
          ]},
        { id:3, title:'Machine Learning', duration:'6–8 weeks',
          description:'Understand and implement classical ML algorithms.',
          topics:['Linear & Logistic Regression','Decision Trees & Random Forests','SVM & KNN','Clustering (K-Means)','Model Evaluation & Cross-Validation'],
          resources:[
            {title:'ML Course',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Scikit-learn Docs',url:'https://scikit-learn.org',type:'docs'},
          ]},
        { id:4, title:'Deep Learning', duration:'8–12 weeks',
          description:'Neural networks power modern AI. Learn to build and train deep neural networks.',
          topics:['Neural Network Fundamentals','Backpropagation & Optimization','CNNs (Computer Vision)','RNNs / LSTMs','Transformers & Attention','TensorFlow / PyTorch'],
          resources:[
            {title:'Deep Learning',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Fast.ai Course',url:'https://course.fast.ai',type:'docs'},
          ]},
        { id:5, title:'NLP & Large Language Models', duration:'6–8 weeks',
          description:'NLP and LLMs are the hottest area in AI.',
          topics:['Text Preprocessing & Tokenization','Word Embeddings','Transformers (BERT, GPT)','Hugging Face Transformers','Fine-tuning LLMs','Prompt Engineering'],
          resources:[
            {title:'Hugging Face Course',url:'https://huggingface.co/course',type:'docs'},
            {title:'NLP Tutorial',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
        { id:6, title:'MLOps & Deployment', duration:'4–6 weeks',
          description:'Deploy ML models to production with monitoring and scalability.',
          topics:['Model Serialization','FastAPI for ML Serving','Docker for ML','MLflow Experiment Tracking','CI/CD for ML','Model Monitoring'],
          resources:[
            {title:'MLOps Tutorial',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
      ]
    },
    {
      id: 'applied-ai', title: 'Applied AI Engineer', shortTitle: 'Applied AI', icon: '✨',
      description: 'Build AI-powered products using LLM APIs, RAG systems, and Generative AI tools.',
      color: '#e879f9', gradient: 'linear-gradient(135deg,#e879f9,#f43f5e)',
      duration: '8–12 months', difficulty: 'Intermediate–Advanced', tags: ['LLMs','RAG','Generative AI'],
      steps: [
        { id:1, title:'Python & API Basics', duration:'3–4 weeks',
          description:'Applied AI engineering requires Python for scripting and API integration.',
          topics:['Python Fundamentals','REST APIs with requests','Environment Variables & Secrets','JSON Handling'],
          resources:[
            {title:'Python Crash Course',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
          ]},
        { id:2, title:'LLM APIs (OpenAI, Gemini)', duration:'3–4 weeks',
          description:'Learn to work with LLM APIs to build AI-powered features.',
          topics:['OpenAI API (GPT-4o)','Google Gemini API','Chat Completions & Streaming','Function Calling / Tool Use','Token Management & Cost Optimization'],
          resources:[
            {title:'OpenAI Docs',url:'https://platform.openai.com/docs',type:'docs'},
            {title:'Google AI Studio',url:'https://aistudio.google.com',type:'docs'},
          ]},
        { id:3, title:'Prompt Engineering', duration:'2–3 weeks',
          description:'Learn to craft effective prompts to get the best out of LLMs.',
          topics:['Zero-shot & Few-shot Prompting','Chain-of-Thought Prompting','System Prompts','Prompt Templates','Evaluation of Prompts'],
          resources:[
            {title:'Prompt Engineering Guide',url:'https://promptingguide.ai',type:'docs'},
          ]},
        { id:4, title:'RAG Systems', duration:'4–6 weeks',
          description:'Build Retrieval-Augmented Generation systems to give LLMs knowledge of your data.',
          topics:['Embeddings & Vector Databases (Pinecone, Chroma)','LangChain Framework','LlamaIndex','Document Loaders & Chunking','Semantic Search','RAG Pipeline End-to-End'],
          resources:[
            {title:'LangChain Tutorial',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'LangChain Docs',url:'https://python.langchain.com',type:'docs'},
          ]},
        { id:5, title:'AI Agents & Apps', duration:'4–6 weeks',
          description:'Build autonomous AI agents and deploy AI applications.',
          topics:['AI Agent Concepts (ReAct Pattern)','Tool Calling & Function Agents','LangGraph','CrewAI Framework','Streamlit for AI Apps','Deploy to Hugging Face Spaces'],
          resources:[
            {title:'Hugging Face Spaces',url:'https://huggingface.co/spaces',type:'docs'},
          ]},
      ]
    },
    {
      id: 'fullstack', title: 'Full Stack Web Developer', shortTitle: 'Full Stack', icon: '🌐',
      description: 'Build complete web applications from frontend to backend with databases and deployment.',
      color: '#14b8a6', gradient: 'linear-gradient(135deg,#14b8a6,#3b82f6)',
      duration: '12–16 months', difficulty: 'Intermediate', tags: ['React','Node.js','MongoDB'],
      steps: [
        { id:1, title:'Frontend Foundations (HTML/CSS/JS)', duration:'4–6 weeks',
          description:'HTML, CSS, and JavaScript are the pillars of every web app.',
          topics:['HTML5 & Semantic Elements','CSS Flexbox & Grid','JavaScript ES6+','DOM Manipulation','Responsive Design'],
          resources:[
            {title:'HTML CSS JS Bootcamp',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'freeCodeCamp',url:'https://freecodecamp.org',type:'docs'},
          ]},
        { id:2, title:'React.js for Frontend', duration:'6–8 weeks',
          description:'Build component-based UIs with the most popular JS framework.',
          topics:['React Components & JSX','Hooks (useState, useEffect)','Context API','React Router','Axios / Fetch','Material UI / Chakra UI'],
          resources:[
            {title:'React Crash Course',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'React Docs',url:'https://react.dev',type:'docs'},
          ]},
        { id:3, title:'Node.js + Express Backend', duration:'4–6 weeks',
          description:'Build the server-side with Node.js and Express.',
          topics:['Node.js Core','Express.js REST APIs','Middleware','File Uploads (Multer)','WebSockets (Socket.io)'],
          resources:[
            {title:'Node.js & Express Tutorial',url:'https://www.youtube.com/@NetNinja',type:'youtube',channel:'The Net Ninja'},
          ]},
        { id:4, title:'Databases & Auth', duration:'4–6 weeks',
          description:'Store data with MongoDB and SQL. Secure with JWT auth.',
          topics:['MongoDB & Mongoose','PostgreSQL / MySQL','CRUD Operations','JWT Authentication','OAuth (Google/GitHub Login)','Protected Routes'],
          resources:[
            {title:'MongoDB Crash Course',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
          ]},
        { id:5, title:'Full Stack Project & Deployment', duration:'4–6 weeks',
          description:'Build a complete MERN/PERN stack project and deploy it.',
          topics:['MERN Stack Project','Environment Config','Deploy Frontend (Vercel)','Deploy Backend (Render/Railway)','Docker Basics','Domain & SSL Setup'],
          resources:[
            {title:'MERN Stack Tutorial',url:'https://www.youtube.com/@NetNinja',type:'youtube',channel:'The Net Ninja'},
          ]},
      ]
    },
    {
      id: 'data-scientist', title: 'Data Scientist / ML Engineer', shortTitle: 'Data Sci / ML', icon: '🔬',
      description: 'Extract insights from data and build machine learning models that power intelligent systems.',
      color: '#06b6d4', gradient: 'linear-gradient(135deg,#06b6d4,#a855f7)',
      duration: '14–20 months', difficulty: 'Advanced', tags: ['Python','ML','Deep Learning'],
      steps: [
        { id:1, title:'Python & Scientific Stack', duration:'4–6 weeks',
          description:'Master Python with NumPy, Pandas, and Matplotlib for data manipulation.',
          topics:['Python Basics','NumPy Arrays & Operations','Pandas DataFrames','Matplotlib & Seaborn','Jupyter Notebooks'],
          resources:[
            {title:'Python Data Science',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Kaggle Learn',url:'https://kaggle.com/learn',type:'docs'},
          ]},
        { id:2, title:'Statistics & Probability', duration:'4–6 weeks',
          description:'The mathematical foundation of all ML algorithms.',
          topics:['Descriptive & Inferential Stats','Probability Distributions','Bayes Theorem','Hypothesis Testing','Correlation vs Causation'],
          resources:[
            {title:'StatQuest',url:'https://www.youtube.com/@statquest',type:'youtube',channel:'StatQuest'},
          ]},
        { id:3, title:'Machine Learning', duration:'6–8 weeks',
          description:'Implement and understand ML algorithms for classification, regression, and clustering.',
          topics:['Supervised Learning','Unsupervised Learning','Model Evaluation (F1, AUC)','Cross-Validation','Hyperparameter Tuning','Scikit-learn'],
          resources:[
            {title:'ML Playlist',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Scikit-learn Docs',url:'https://scikit-learn.org',type:'docs'},
          ]},
        { id:4, title:'Deep Learning', duration:'6–8 weeks',
          description:'Build neural networks for images, text, and time series data.',
          topics:['Neural Network Basics','CNNs for Vision','RNNs for Sequences','Transfer Learning','TensorFlow & Keras','PyTorch'],
          resources:[
            {title:'Fast.ai',url:'https://course.fast.ai',type:'docs'},
          ]},
        { id:5, title:'Model Deployment & Projects', duration:'4–6 weeks',
          description:'Deploy ML models and build a Kaggle/GitHub portfolio.',
          topics:['Flask / FastAPI for ML APIs','Streamlit Dashboards','Docker for ML','Kaggle Competition Projects','Model Versioning (MLflow)'],
          resources:[
            {title:'Model Deployment Tutorial',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Kaggle Competitions',url:'https://kaggle.com/competitions',type:'practice'},
          ]},
      ]
    },
    {
      id: 'devops', title: 'DevOps & Cloud Engineer', shortTitle: 'DevOps', icon: '☁️',
      description: 'Automate software delivery pipelines and manage cloud infrastructure for scalable systems.',
      color: '#f59e0b', gradient: 'linear-gradient(135deg,#f59e0b,#f97316)',
      duration: '10–14 months', difficulty: 'Intermediate–Advanced', tags: ['Docker','Kubernetes','AWS'],
      steps: [
        { id:1, title:'Linux & Shell Scripting', duration:'3–4 weeks',
          description:'Linux is the foundation of all DevOps. Learn to navigate and automate.',
          topics:['Linux File System & Commands','User & Permissions','Shell Scripting (bash)','Process Management','Cron Jobs','SSH'],
          resources:[
            {title:'Linux for Beginners',url:'https://www.youtube.com/@NetworkChuck',type:'youtube',channel:'NetworkChuck'},
          ]},
        { id:2, title:'Docker', duration:'3–4 weeks',
          description:'Containerize applications for consistent deployment.',
          topics:['Docker Architecture','Dockerfile & Images','Containers & Networking','Volumes','Docker Compose','Container Registry'],
          resources:[
            {title:'Docker Full Course',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
            {title:'Docker Docs',url:'https://docs.docker.com',type:'docs'},
          ]},
        { id:3, title:'Kubernetes', duration:'4–6 weeks',
          description:'Orchestrate containerized applications at scale.',
          topics:['K8s Architecture (Pods, Nodes)','Deployments & Services','ConfigMaps & Secrets','Ingress Controllers','Helm Charts'],
          resources:[
            {title:'Kubernetes Tutorial',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
            {title:'Kubernetes Docs',url:'https://kubernetes.io/docs/',type:'docs'},
          ]},
        { id:4, title:'CI/CD Pipelines', duration:'3–4 weeks',
          description:'Automate building, testing, and deploying code.',
          topics:['GitHub Actions','Jenkins','GitLab CI/CD','ArgoCD (GitOps)'],
          resources:[
            {title:'GitHub Actions Tutorial',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
          ]},
        { id:5, title:'Cloud (AWS / GCP / Azure)', duration:'4–6 weeks',
          description:'Learn one cloud platform deeply. AWS is the most popular.',
          topics:['EC2, S3, RDS, Lambda','IAM & Security','VPC Networking','ECS / EKS for Containers','CloudWatch Monitoring'],
          resources:[
            {title:'AWS Full Course',url:'https://www.youtube.com/@NetworkChuck',type:'youtube',channel:'NetworkChuck'},
            {title:'AWS Free Tier',url:'https://aws.amazon.com/free/',type:'docs'},
          ]},
        { id:6, title:'Infrastructure as Code', duration:'2–3 weeks',
          description:'Manage infrastructure using code for reproducibility.',
          topics:['Terraform Basics','Terraform Plans','Ansible Automation','IaC Best Practices'],
          resources:[
            {title:'Terraform Tutorial',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
          ]},
      ]
    },
    {
      id: 'android', title: 'Android Developer', shortTitle: 'Android Dev', icon: '📱',
      description: 'Build native Android applications using Kotlin, Jetpack Compose, and Android SDK.',
      color: '#16a34a', gradient: 'linear-gradient(135deg,#16a34a,#86efac)',
      duration: '10–14 months', difficulty: 'Intermediate', tags: ['Kotlin','Jetpack','Android'],
      steps: [
        { id:1, title:'Kotlin Programming', duration:'4–6 weeks',
          description:'Kotlin is the modern, preferred language for Android development.',
          topics:['Kotlin Basics','OOP in Kotlin','Null Safety','Coroutines','Extension Functions','Data Classes'],
          resources:[
            {title:'Kotlin Full Course',url:'https://www.youtube.com/@PhilippLackner',type:'youtube',channel:'Philipp Lackner'},
            {title:'Kotlin Docs',url:'https://kotlinlang.org/docs/',type:'docs'},
          ]},
        { id:2, title:'Android Fundamentals', duration:'4–6 weeks',
          description:'Learn the core components of Android: Activities, Fragments, and Intents.',
          topics:['Android Studio Setup','Activity Lifecycle','Fragments','Intents & Navigation','Permissions','Android Manifest'],
          resources:[
            {title:'Android Developer Docs',url:'https://developer.android.com/docs',type:'docs'},
          ]},
        { id:3, title:'Jetpack Compose (Modern UI)', duration:'4–6 weeks',
          description:'Build beautiful, declarative UIs using Jetpack Compose.',
          topics:['Composable Functions','State & Recomposition','Layouts & Modifiers','Navigation Component','Material Design 3','Animations'],
          resources:[
            {title:'Jetpack Compose Tutorial',url:'https://www.youtube.com/@PhilippLackner',type:'youtube',channel:'Philipp Lackner'},
            {title:'Compose Docs',url:'https://developer.android.com/jetpack/compose',type:'docs'},
          ]},
        { id:4, title:'Networking, Storage & Firebase', duration:'4–6 weeks',
          description:'Connect your app to APIs, store data locally, and use Firebase.',
          topics:['Retrofit for HTTP Requests','Room Database','LiveData & Flow','Firebase Auth & Firestore','Push Notifications (FCM)','Play Store Publishing'],
          resources:[
            {title:'Firebase Docs',url:'https://firebase.google.com/docs',type:'docs'},
          ]},
      ]
    },
    {
      id: 'cybersecurity', title: 'CyberSecurity Analyst', shortTitle: 'CyberSecurity', icon: '🔐',
      description: 'Protect systems and networks from cyber threats through ethical hacking and security analysis.',
      color: '#dc2626', gradient: 'linear-gradient(135deg,#dc2626,#7f1d1d)',
      duration: '10–16 months', difficulty: 'Intermediate–Advanced', tags: ['Networking','Ethical Hacking','Security'],
      steps: [
        { id:1, title:'Networking Fundamentals', duration:'4–6 weeks',
          description:'You cannot secure what you don\'t understand. Master networking basics first.',
          topics:['OSI & TCP/IP Model','Protocols (HTTP, DNS, FTP, SSH)','IP Addressing & Subnetting','Firewalls & Proxies','Wireshark Packet Analysis'],
          resources:[
            {title:'Networking for Hackers',url:'https://www.youtube.com/@NetworkChuck',type:'youtube',channel:'NetworkChuck'},
            {title:'Professor Messer',url:'https://www.youtube.com/@professormesser',type:'youtube',channel:'Professor Messer'},
          ]},
        { id:2, title:'Linux & Kali Linux', duration:'3–4 weeks',
          description:'Kali Linux is the standard hacking OS. Get comfortable with the terminal.',
          topics:['Kali Linux Setup','Linux Commands','File Permissions','Process & Network Commands','Bash Scripting for Security'],
          resources:[
            {title:'Kali Linux Tutorial',url:'https://www.youtube.com/@NetworkChuck',type:'youtube',channel:'NetworkChuck'},
          ]},
        { id:3, title:'Ethical Hacking & Pen Testing', duration:'6–8 weeks',
          description:'Learn to legally hack systems to find and fix vulnerabilities.',
          topics:['Reconnaissance (OSINT)','Scanning (Nmap, Nessus)','Exploitation (Metasploit)','Privilege Escalation','Web App Hacking (Burp Suite)','Reporting'],
          resources:[
            {title:'Ethical Hacking Course',url:'https://www.youtube.com/@TCMSecurityAcademy',type:'youtube',channel:'TCM Security'},
            {title:'TryHackMe',url:'https://tryhackme.com',type:'practice'},
            {title:'HackTheBox',url:'https://hackthebox.com',type:'practice'},
          ]},
        { id:4, title:'Web Application Security', duration:'4–6 weeks',
          description:'Understand and exploit common web vulnerabilities.',
          topics:['OWASP Top 10','SQL Injection','XSS & CSRF','Broken Authentication','Burp Suite for Web Testing'],
          resources:[
            {title:'OWASP Top 10',url:'https://owasp.org/Top10/',type:'docs'},
            {title:'PortSwigger Web Security',url:'https://portswigger.net/web-security',type:'practice'},
          ]},
        { id:5, title:'Certifications', duration:'2–4 months',
          description:'Earn industry-recognized certifications to boost your career.',
          topics:['CompTIA Security+','CEH (Certified Ethical Hacker)','OSCP (Advanced)','eJPT (Beginner-friendly)'],
          resources:[
            {title:'CompTIA Security+ Study',url:'https://www.youtube.com/@professormesser',type:'youtube',channel:'Professor Messer'},
          ]},
      ]
    },
    {
      id: 'uiux', title: 'UI/UX Designer', shortTitle: 'UI/UX Designer', icon: '🎭',
      description: 'Design beautiful, user-centered digital products using Figma and modern UX principles.',
      color: '#ec4899', gradient: 'linear-gradient(135deg,#ec4899,#f97316)',
      duration: '8–12 months', difficulty: 'Beginner–Intermediate', tags: ['Figma','UX Research','Prototyping'],
      steps: [
        { id:1, title:'Design Fundamentals', duration:'3–4 weeks',
          description:'Learn the core principles of visual design.',
          topics:['Color Theory','Typography Principles','Layout & Hierarchy','Grid Systems','Visual Balance & Contrast','White Space Usage'],
          resources:[
            {title:'UI Design Fundamentals',url:'https://www.youtube.com/@DesignCourse',type:'youtube',channel:'DesignCourse'},
          ]},
        { id:2, title:'Figma Mastery', duration:'4–6 weeks',
          description:'Figma is the industry-standard design tool. Master it completely.',
          topics:['Figma Interface & Basics','Frames, Components & Variants','Auto Layout','Styles & Design Tokens','Prototyping & Interactions','Handoff to Developers'],
          resources:[
            {title:'Figma Full Course',url:'https://www.youtube.com/@DesignCourse',type:'youtube',channel:'DesignCourse'},
            {title:'Figma Official Tutorials',url:'https://www.figma.com/resources/learn-design/',type:'docs'},
          ]},
        { id:3, title:'UX Research', duration:'3–4 weeks',
          description:'Good design starts with understanding users.',
          topics:['User Personas','User Journey Maps','Usability Testing','A/B Testing','Surveys & Interviews'],
          resources:[
            {title:'Nielsen Norman Group',url:'https://nngroup.com/articles/',type:'docs'},
          ]},
        { id:4, title:'Design Systems & Portfolio', duration:'1–2 months',
          description:'Build consistent design systems and an impressive portfolio.',
          topics:['Component Libraries','Design Tokens','Accessibility (WCAG)','Case Study Writing','Behance / Dribbble Portfolio'],
          resources:[
            {title:'Material Design Guidelines',url:'https://m3.material.io',type:'docs'},
            {title:'Dribbble',url:'https://dribbble.com',type:'docs'},
          ]},
      ]
    },
    {
      id: 'cp', title: 'Competitive Programmer', shortTitle: 'Competitive Prog.', icon: '🏆',
      description: 'Master algorithms and problem-solving to excel in competitive programming contests worldwide.',
      color: '#d97706', gradient: 'linear-gradient(135deg,#d97706,#fbbf24)',
      duration: '12–24 months', difficulty: 'Expert', tags: ['C++','Algorithms','Contests'],
      steps: [
        { id:1, title:'C++ & STL Mastery', duration:'4–6 weeks',
          description:'C++ is the go-to language for CP due to its speed and STL.',
          topics:['C++ Syntax & I/O','STL Containers (vector, map, set)','STL Algorithms','Time & Space Complexity','Bit Manipulation'],
          resources:[
            {title:'CP C++ STL',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
            {title:'CP-Algorithms',url:'https://cp-algorithms.com',type:'docs'},
          ]},
        { id:2, title:'Core Algorithms', duration:'6–8 weeks',
          description:'Essential algorithms that appear in every CP contest.',
          topics:['Binary Search & Two Pointers','Sorting Algorithms','Divide & Conquer','Greedy Algorithms','Recursion & Backtracking'],
          resources:[
            {title:'CSES Problem Set',url:'https://cses.fi/problemset',type:'practice'},
          ]},
        { id:3, title:'Graph Algorithms', duration:'4–6 weeks',
          description:'Graphs are the most important topic in CP.',
          topics:['BFS & DFS','Shortest Paths (Dijkstra, Bellman-Ford)','MST (Kruskal, Prim)','Topological Sort','Disjoint Set Union (DSU)'],
          resources:[
            {title:'Graph Series',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
          ]},
        { id:4, title:'Dynamic Programming', duration:'6–8 weeks',
          description:'DP is the hardest and most rewarding topic in CP.',
          topics:['Memoization & Tabulation','Classical DP (Knapsack, LCS, LIS)','Bitmask DP','DP on Trees','DP Optimization'],
          resources:[
            {title:'DP Full Series',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
            {title:'AtCoder DP Contest',url:'https://atcoder.jp/contests/dp',type:'practice'},
          ]},
        { id:5, title:'Advanced Topics & Contests', duration:'3–4 months',
          description:'Advanced data structures and regular contest participation.',
          topics:['Segment Trees & Fenwick Tree','Trie','Number Theory','String Algorithms (KMP, Z-function)','Codeforces Contests','AtCoder'],
          resources:[
            {title:'Codeforces',url:'https://codeforces.com',type:'practice'},
            {title:'AtCoder',url:'https://atcoder.jp',type:'practice'},
            {title:'LeetCode',url:'https://leetcode.com',type:'practice'},
          ]},
      ]
    },
  ],

  subjects: [
    {
      id: 'web-dev', title: 'Web Development', icon: '🌐',
      description: 'Learn to build modern websites and web applications from scratch to deployment.',
      color: '#3b82f6', gradient: 'linear-gradient(135deg,#3b82f6,#8b5cf6)',
      duration: '6–10 months', difficulty: 'Beginner–Intermediate', tags: ['HTML','CSS','JavaScript'],
      steps: [
        { id:1, title:'HTML Fundamentals', duration:'1–2 weeks',
          description:'HTML is the skeleton of every web page.',
          topics:['HTML Document Structure','Semantic Tags','Forms & Inputs','Tables & Lists','Multimedia Tags'],
          resources:[
            {title:'HTML Tutorial',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'MDN HTML Reference',url:'https://developer.mozilla.org/en-US/docs/Web/HTML',type:'docs'},
          ]},
        { id:2, title:'CSS & Responsive Design', duration:'2–3 weeks',
          description:'Style your pages beautifully and make them responsive.',
          topics:['Box Model','Flexbox & Grid','Responsive Design & Media Queries','CSS Animations','CSS Variables'],
          resources:[
            {title:'CSS Flexbox & Grid',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'CSS Tricks',url:'https://css-tricks.com',type:'docs'},
          ]},
        { id:3, title:'JavaScript Essentials', duration:'4–6 weeks',
          description:'Add interactivity and logic to your web pages.',
          topics:['Variables, Functions, Loops','DOM Manipulation','Events','Fetch API','Promises & async/await','ES6+ Features'],
          resources:[
            {title:'JavaScript Tutorial',url:'https://www.youtube.com/@Fireship',type:'youtube',channel:'Fireship'},
            {title:'JavaScript.info',url:'https://javascript.info',type:'docs'},
          ]},
        { id:4, title:'React.js Framework', duration:'4–6 weeks',
          description:'Build component-based web apps with the most popular JS library.',
          topics:['Components & Props','State & Hooks','React Router','API Integration'],
          resources:[
            {title:'React Tutorial',url:'https://www.youtube.com/@NetNinja',type:'youtube',channel:'The Net Ninja'},
            {title:'React Docs',url:'https://react.dev',type:'docs'},
          ]},
        { id:5, title:'Backend with Node.js', duration:'4–6 weeks',
          description:'Build server-side applications and REST APIs.',
          topics:['Node.js Basics','Express.js','REST APIs','Database Integration','Authentication'],
          resources:[
            {title:'Node.js Tutorial',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
          ]},
        { id:6, title:'Deployment & Hosting', duration:'1–2 weeks',
          description:'Deploy your websites to the internet.',
          topics:['GitHub Pages','Vercel','Netlify','Custom Domain Setup','HTTPS & SSL'],
          resources:[
            {title:'Vercel Docs',url:'https://vercel.com/docs',type:'docs'},
          ]},
      ]
    },
    {
      id: 'dbms', title: 'Database Management System (SQL)', icon: '🗄️',
      description: 'Learn to design, query, and optimize relational databases using SQL.',
      color: '#0369a1', gradient: 'linear-gradient(135deg,#0369a1,#0891b2)',
      duration: '2–3 months', difficulty: 'Intermediate', tags: ['SQL','Normalization','ACID'],
      steps: [
        { id:1, title:'Database Fundamentals', duration:'1 week',
          description:'Understand what databases are and how they work.',
          topics:['What is a Database?','DBMS vs File System','Types of Databases','Schema & Tables','Keys (Primary, Foreign, Candidate)'],
          resources:[
            {title:'DBMS Introduction',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:2, title:'SQL — DDL & DML', duration:'3–4 weeks',
          description:'Learn to create, modify, and query databases with SQL.',
          topics:['CREATE, ALTER, DROP (DDL)','INSERT, UPDATE, DELETE (DML)','SELECT & WHERE Clauses','ORDER BY & LIMIT','Aggregate Functions'],
          resources:[
            {title:'SQL Full Course',url:'https://www.youtube.com/@techTFQ',type:'youtube',channel:'techTFQ'},
            {title:'SQLZoo',url:'https://sqlzoo.net',type:'practice'},
          ]},
        { id:3, title:'Advanced SQL', duration:'3–4 weeks',
          description:'Master complex queries and database features.',
          topics:['JOINs (INNER, LEFT, RIGHT, FULL)','Subqueries & Nested Queries','CTEs (WITH Clause)','Window Functions','Views & Stored Procedures','Triggers'],
          resources:[
            {title:'Advanced SQL Tutorial',url:'https://www.youtube.com/@techTFQ',type:'youtube',channel:'techTFQ'},
            {title:'LeetCode SQL',url:'https://leetcode.com/problemset/database/',type:'practice'},
          ]},
        { id:4, title:'Normalization', duration:'1–2 weeks',
          description:'Design efficient database schemas by eliminating redundancy.',
          topics:['Functional Dependencies','1NF, 2NF, 3NF, BCNF','Decomposition','Lossless Join Property'],
          resources:[
            {title:'Normalization Series',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:5, title:'Transactions, Indexing & Optimization', duration:'2 weeks',
          description:'Ensure data integrity and make your queries blazing fast.',
          topics:['ACID Properties','Transactions & Rollback','Isolation Levels','Deadlock in Databases','B-Tree & Hash Indexes','Query Optimization'],
          resources:[
            {title:'ACID & Transactions',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
      ]
    },
    {
      id: 'python', title: 'Python Programming', icon: '🐍',
      description: 'Master Python from basics to advanced — the world\'s most versatile programming language.',
      color: '#1d4ed8', gradient: 'linear-gradient(135deg,#1d4ed8,#facc15)',
      duration: '3–5 months', difficulty: 'Beginner', tags: ['Python','OOP','Libraries'],
      steps: [
        { id:1, title:'Python Basics', duration:'2–3 weeks',
          description:'Get started with the most beginner-friendly language.',
          topics:['Installation & Setup','Variables & Data Types','Input/Output','Operators','String Manipulation'],
          resources:[
            {title:'Python Tutorial (Hindi)',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'Python Docs',url:'https://docs.python.org/3/',type:'docs'},
          ]},
        { id:2, title:'Control Flow & Functions', duration:'2–3 weeks',
          description:'Write logic-based programs with conditions, loops, and functions.',
          topics:['if/elif/else','for & while Loops','Functions & Parameters','Lambda Functions','Recursion','Scope (LEGB Rule)'],
          resources:[
            {title:'Python Functions Tutorial',url:'https://www.youtube.com/@sentdex',type:'youtube',channel:'sentdex'},
          ]},
        { id:3, title:'Data Structures in Python', duration:'2–3 weeks',
          description:'Use Python\'s built-in data structures for efficient programming.',
          topics:['Lists, Tuples, Sets','Dictionaries','List Comprehensions','Stack & Queue using Collections','Sorting & Searching'],
          resources:[
            {title:'Python Data Structures',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
          ]},
        { id:4, title:'OOP in Python', duration:'2–3 weeks',
          description:'Write modular and reusable code using OOP.',
          topics:['Classes & Objects','Constructors & Destructors','Inheritance & Polymorphism','Encapsulation','Magic Methods'],
          resources:[
            {title:'OOP in Python',url:'https://www.youtube.com/@programmingwithmosh',type:'youtube',channel:'Programming with Mosh'},
          ]},
        { id:5, title:'Advanced Python & Projects', duration:'3–4 weeks',
          description:'Level up with advanced Python and build real-world projects.',
          topics:['Decorators & Closures','Generators','Regular Expressions','Web Scraping (requests, BeautifulSoup)','3 Mini Projects'],
          resources:[
            {title:'Advanced Python',url:'https://www.youtube.com/@sentdex',type:'youtube',channel:'sentdex'},
            {title:'Python Projects',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
          ]},
      ]
    },
    {
      id: 'javascript', title: 'JavaScript (Node & React)', icon: '⚛️',
      description: 'Master JavaScript from web scripting to full-stack development with React and Node.js.',
      color: '#ca8a04', gradient: 'linear-gradient(135deg,#ca8a04,#3b82f6)',
      duration: '5–8 months', difficulty: 'Intermediate', tags: ['JavaScript','React','Node.js'],
      steps: [
        { id:1, title:'JavaScript Fundamentals', duration:'4–6 weeks',
          description:'Build a rock-solid foundation in the language of the web.',
          topics:['Variables (var/let/const)','Data Types & Type Coercion','Functions & Arrow Functions','Arrays & Objects','ES6+ Features (Spread, Destructuring)','Modules (import/export)'],
          resources:[
            {title:'JavaScript Full Course',url:'https://www.youtube.com/@Fireship',type:'youtube',channel:'Fireship'},
            {title:'JavaScript.info',url:'https://javascript.info',type:'docs'},
          ]},
        { id:2, title:'Asynchronous JavaScript', duration:'2–3 weeks',
          description:'Handle async operations gracefully — a must-know for modern JS.',
          topics:['Callbacks & Callback Hell','Promises','async/await','Fetch API','Error Handling with try/catch','Event Loop Understanding'],
          resources:[
            {title:'Async JavaScript',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
          ]},
        { id:3, title:'React.js', duration:'6–8 weeks',
          description:'Build modern, interactive UIs with the most popular UI library.',
          topics:['JSX & Rendering','Components (Functional & Class)','State & Props','Hooks (useState, useEffect, useRef)','Context API','React Router v6'],
          resources:[
            {title:'React Course',url:'https://www.youtube.com/@NetNinja',type:'youtube',channel:'The Net Ninja'},
            {title:'React Docs',url:'https://react.dev',type:'docs'},
          ]},
        { id:4, title:'Node.js & Full Stack', duration:'4–6 weeks',
          description:'Run JavaScript on the server and build a full-stack app.',
          topics:['Node.js Runtime','Express.js','REST API Building','MERN Stack Architecture','JWT Auth End-to-End','Deploy with Render + Vercel'],
          resources:[
            {title:'Node.js Crash Course',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'MERN Stack Project',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
          ]},
      ]
    },
    {
      id: 'dsa', title: 'Data Structures & Algorithms', icon: '🔮',
      description: 'The foundation of programming excellence. Master DSA for competitive coding and top company interviews.',
      color: '#7c3aed', gradient: 'linear-gradient(135deg,#7c3aed,#a78bfa)',
      duration: '4–6 months', difficulty: 'Intermediate–Advanced', tags: ['Algorithms','Problem Solving','Coding Interviews'],
      steps: [
        { id:1, title:'Arrays & Strings', duration:'3–4 weeks',
          description:'The most fundamental and frequently tested data structures.',
          topics:['Array Traversal & Manipulation','Two Pointers Technique','Sliding Window','Prefix Sums','String Patterns','Hashing for O(1) lookups'],
          resources:[
            {title:'Arrays & Strings - Striver',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
            {title:'LeetCode Arrays',url:'https://leetcode.com/explore/learn/card/array-and-string/',type:'practice'},
          ]},
        { id:2, title:'Linked Lists, Stacks & Queues', duration:'3–4 weeks',
          description:'Dynamic data structures critical for interviews.',
          topics:['Singly & Doubly Linked Lists','Reversal & Cycle Detection','Stack Implementation & Monotonic Stack','Queue & Deque','Priority Queue / Heap'],
          resources:[
            {title:'Linked Lists - Apna College',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'Stacks & Queues',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
          ]},
        { id:3, title:'Trees & Binary Trees', duration:'4–5 weeks',
          description:'Hierarchical structures used everywhere in CS.',
          topics:['Tree Traversals (Inorder, Preorder, Postorder)','BST Operations','Height, Diameter, Balance','LCA & Path Problems','Segment Trees','Tries'],
          resources:[
            {title:'Trees Playlist',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
          ]},
        { id:4, title:'Graphs', duration:'4–6 weeks',
          description:'The most powerful and complex data structure in CS.',
          topics:['BFS & DFS Traversal','Topological Sort','Shortest Path (Dijkstra, Bellman-Ford)','MST (Kruskal, Prim)','Union Find / DSU'],
          resources:[
            {title:'Graph Series',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
          ]},
        { id:5, title:'Dynamic Programming', duration:'6–8 weeks',
          description:'Solve complex problems by breaking them into overlapping subproblems.',
          topics:['1D & 2D DP','Knapsack Variants','Longest Subsequences (LCS, LIS)','Interval & Partition DP','DP on Trees'],
          resources:[
            {title:'DP Series',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
            {title:'AtCoder DP Contest',url:'https://atcoder.jp/contests/dp',type:'practice'},
          ]},
      ]
    },
    {
      id: 'ai', title: 'Artificial Intelligence', icon: '🤖',
      description: 'Explore the theory and practice of artificial intelligence from search algorithms to modern AI.',
      color: '#8b5cf6', gradient: 'linear-gradient(135deg,#8b5cf6,#6d28d9)',
      duration: '4–6 months', difficulty: 'Advanced', tags: ['Search','Knowledge','Machine Learning'],
      steps: [
        { id:1, title:'Introduction to AI', duration:'1 week',
          description:'Understand what AI is, its history, and the Turing Test.',
          topics:['What is AI?','Types of AI','Turing Test & Rationality','AI Applications & Ethics'],
          resources:[
            {title:'MIT AI Course',url:'https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/',type:'docs'},
          ]},
        { id:2, title:'Search & Problem Solving', duration:'3–4 weeks',
          description:'Foundational AI algorithms for problem-solving and game playing.',
          topics:['BFS & DFS for AI','A* Search','Greedy Search','Minimax Algorithm','Alpha-Beta Pruning'],
          resources:[
            {title:'AI Search Algorithms',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:3, title:'Knowledge Representation', duration:'2–3 weeks',
          description:'Represent real-world knowledge for AI systems to reason about.',
          topics:['Propositional Logic','First-Order Logic','Knowledge Graphs','Expert Systems','Bayesian Networks'],
          resources:[
            {title:'Knowledge Representation',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:4, title:'Machine Learning Fundamentals', duration:'4–6 weeks',
          description:'The modern core of AI — teach machines to learn from data.',
          topics:['Types of Learning','Linear & Logistic Regression','Decision Trees','Feature Engineering','Model Evaluation'],
          resources:[
            {title:'ML Course',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
        { id:5, title:'Deep Learning & NLP', duration:'4–6 weeks',
          description:'The technology powering modern AI breakthroughs.',
          topics:['Neural Networks (MLP, CNN, RNN)','Transformers & BERT','Generative AI (GANs, VAEs)','Chatbots & LLMs'],
          resources:[
            {title:'Deep Learning - 3Blue1Brown',url:'https://www.youtube.com/@3blue1brown',type:'youtube',channel:'3Blue1Brown'},
            {title:'NLP Tutorial',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
      ]
    },
    {
      id: 'ml', title: 'Machine Learning', icon: '🧠',
      description: 'Build intelligent systems that learn from data using Python and modern ML libraries.',
      color: '#059669', gradient: 'linear-gradient(135deg,#059669,#34d399)',
      duration: '4–6 months', difficulty: 'Intermediate–Advanced', tags: ['Scikit-learn','TensorFlow','Data'],
      steps: [
        { id:1, title:'Math for ML', duration:'4–6 weeks',
          description:'Strong math foundation is essential for understanding ML algorithms.',
          topics:['Linear Algebra (Vectors, Matrices, Eigenvalues)','Calculus (Derivatives, Gradient Descent)','Probability & Statistics','Bayes Theorem'],
          resources:[
            {title:'3Blue1Brown Linear Algebra',url:'https://www.youtube.com/@3blue1brown',type:'youtube',channel:'3Blue1Brown'},
            {title:'StatQuest',url:'https://www.youtube.com/@statquest',type:'youtube',channel:'StatQuest'},
          ]},
        { id:2, title:'Supervised Learning', duration:'4–6 weeks',
          description:'Train models on labeled data to make predictions.',
          topics:['Linear Regression','Logistic Regression','K-Nearest Neighbors','SVM','Decision Trees','Random Forests & Boosting'],
          resources:[
            {title:'ML Algorithms',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Scikit-learn Docs',url:'https://scikit-learn.org',type:'docs'},
          ]},
        { id:3, title:'Unsupervised Learning', duration:'2–3 weeks',
          description:'Find hidden patterns in unlabeled data.',
          topics:['K-Means Clustering','Hierarchical Clustering','DBSCAN','PCA (Dimensionality Reduction)','Autoencoders'],
          resources:[
            {title:'Unsupervised Learning',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
        { id:4, title:'Model Evaluation & Tuning', duration:'2–3 weeks',
          description:'Build robust models by properly evaluating and tuning them.',
          topics:['Train/Val/Test Split','Cross-Validation','Confusion Matrix, Precision, Recall, F1','ROC-AUC Curve','Hyperparameter Tuning (Grid Search, Optuna)'],
          resources:[
            {title:'Model Evaluation',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
        { id:5, title:'Deep Learning & Projects', duration:'6–8 weeks',
          description:'Neural networks that power modern AI applications.',
          topics:['ANN & Backpropagation','CNNs for Image Classification','RNNs & LSTMs','Transfer Learning (VGG, ResNet)','TensorFlow / PyTorch','Kaggle Competitions'],
          resources:[
            {title:'Deep Learning Playlist',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Fast.ai Course',url:'https://course.fast.ai',type:'docs'},
            {title:'Kaggle',url:'https://kaggle.com',type:'practice'},
          ]},
      ]
    },
    {
      id: 'data-science', title: 'Data Science', icon: '📈',
      description: 'Combine statistics, programming, and domain expertise to extract insights from data.',
      color: '#0284c7', gradient: 'linear-gradient(135deg,#0284c7,#7c3aed)',
      duration: '6–9 months', difficulty: 'Intermediate', tags: ['Python','Statistics','Visualization'],
      steps: [
        { id:1, title:'Python & Pandas', duration:'4–6 weeks',
          description:'Python is the primary data science language. Master Pandas for data manipulation.',
          topics:['NumPy Fundamentals','Pandas Series & DataFrame','Data Loading (CSV, Excel, JSON)','Groupby, Merge, Pivot'],
          resources:[
            {title:'Pandas Tutorial',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Kaggle Python Course',url:'https://kaggle.com/learn/python',type:'docs'},
          ]},
        { id:2, title:'Statistics & EDA', duration:'4–6 weeks',
          description:'Statistics is the backbone of data science.',
          topics:['Descriptive Statistics','Probability Distributions','Hypothesis Testing','Data Cleaning & Missing Values','Outlier Detection','Univariate & Bivariate Analysis'],
          resources:[
            {title:'Statistics for DS',url:'https://www.youtube.com/@statquest',type:'youtube',channel:'StatQuest'},
            {title:'EDA Tutorial',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
        { id:3, title:'Data Visualization', duration:'2–3 weeks',
          description:'Tell compelling stories with your data through beautiful visuals.',
          topics:['Matplotlib & Seaborn','Plotly Interactive Charts','Tableau / Power BI','Dashboard Design'],
          resources:[
            {title:'Data Visualization',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
          ]},
        { id:4, title:'ML for DS & Projects', duration:'4–6 weeks',
          description:'Apply ML models to solve data science problems and build a portfolio.',
          topics:['Regression & Classification','Clustering','Feature Selection','Ensemble Methods','Kaggle Notebooks','End-to-End Projects'],
          resources:[
            {title:'ML for Data Science',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Kaggle Competitions',url:'https://kaggle.com',type:'practice'},
          ]},
      ]
    },
    {
      id: 'os', title: 'Operating Systems', icon: '💻',
      description: 'Understand how OS manages processes, memory, and hardware — a core CS subject for interviews.',
      color: '#dc2626', gradient: 'linear-gradient(135deg,#dc2626,#f97316)',
      duration: '2–3 months', difficulty: 'Intermediate', tags: ['Processes','Memory','File Systems'],
      steps: [
        { id:1, title:'Introduction to OS', duration:'1 week',
          description:'Understand what an operating system does and its different types.',
          topics:['What is an OS?','Types (Batch, Time-Sharing, Real-Time)','OS Services & System Calls','OS Structure (Monolithic, Microkernel)'],
          resources:[
            {title:'OS Introduction',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
            {title:'Neso Academy OS',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
          ]},
        { id:2, title:'Process Management', duration:'3–4 weeks',
          description:'How the OS manages running programs and their scheduling.',
          topics:['Process vs Thread','Process States & PCB','CPU Scheduling (FCFS, SJF, Round Robin)','Context Switching','IPC'],
          resources:[
            {title:'Process Management',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:3, title:'Synchronization & Deadlocks', duration:'3–4 weeks',
          description:'Handle concurrent processes safely without race conditions.',
          topics:['Critical Section Problem','Mutex & Semaphores','Monitors','Deadlock Conditions (Coffman)','Prevention & Recovery','Banker\'s Algorithm'],
          resources:[
            {title:'Synchronization',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:4, title:'Memory Management', duration:'3–4 weeks',
          description:'How OS allocates and manages RAM for multiple processes.',
          topics:['Contiguous Allocation','Paging & Segmentation','Page Tables & TLB','Virtual Memory','Page Replacement (FIFO, LRU, Optimal)','Thrashing'],
          resources:[
            {title:'Memory Management',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:5, title:'File Systems & I/O', duration:'2 weeks',
          description:'How OS organizes and accesses stored data.',
          topics:['File Attributes & Operations','Directory Structure','File Allocation Methods','Disk Scheduling (SSTF, SCAN)','I/O Buffering'],
          resources:[
            {title:'File Systems',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
      ]
    },
    {
      id: 'cn', title: 'Computer Networks', icon: '📡',
      description: 'Learn how computers communicate — from physical cables to HTTP and security protocols.',
      color: '#0891b2', gradient: 'linear-gradient(135deg,#0891b2,#0284c7)',
      duration: '2–3 months', difficulty: 'Intermediate', tags: ['TCP/IP','HTTP','Security'],
      steps: [
        { id:1, title:'Introduction & OSI Model', duration:'2 weeks',
          description:'Understand the layered architecture of computer networks.',
          topics:['What is a Network?','OSI Model (7 Layers)','TCP/IP Model','Layer Functions & Protocols'],
          resources:[
            {title:'OSI Model Explained',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
            {title:'CN - Gate Smashers',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:2, title:'Data Link & Physical Layer', duration:'2 weeks',
          description:'How data is transmitted physically and framed for delivery.',
          topics:['Transmission Media','Encoding Techniques','Framing & Error Detection','CSMA/CD & CSMA/CA','MAC Addressing','Switches & Hubs'],
          resources:[
            {title:'Data Link Layer',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
          ]},
        { id:3, title:'Network Layer (IP & Routing)', duration:'3 weeks',
          description:'How packets are routed across networks.',
          topics:['IP Addressing (IPv4 & IPv6)','Subnetting & CIDR','Routing Algorithms','NAT','ICMP','ARP'],
          resources:[
            {title:'Network Layer',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
          ]},
        { id:4, title:'Transport Layer (TCP/UDP)', duration:'2 weeks',
          description:'Reliable vs unreliable data transport between applications.',
          topics:['TCP vs UDP','Three-Way Handshake','Flow Control & Congestion Control','Port Numbers','Socket Programming Basics'],
          resources:[
            {title:'TCP/UDP',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
          ]},
        { id:5, title:'Application Layer', duration:'2 weeks',
          description:'Protocols that power the internet and web.',
          topics:['HTTP & HTTPS','DNS & DHCP','FTP, SSH, SMTP','TLS/SSL','REST & API Communication'],
          resources:[
            {title:'HTTP Deep Dive',url:'https://www.youtube.com/@Fireship',type:'youtube',channel:'Fireship'},
            {title:'Application Layer',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
          ]},
      ]
    },
    {
      id: 'system-design', title: 'System Design', icon: '🏗️',
      description: 'Design large-scale, scalable, and reliable software systems for millions of users.',
      color: '#d97706', gradient: 'linear-gradient(135deg,#d97706,#dc2626)',
      duration: '3–4 months', difficulty: 'Advanced', tags: ['Scalability','Architecture','Distributed Systems'],
      steps: [
        { id:1, title:'Fundamentals of Scalability', duration:'2 weeks',
          description:'Learn the core concepts needed to design scalable systems.',
          topics:['Horizontal vs Vertical Scaling','Latency & Throughput','Availability vs Consistency (CAP)','SLAs & SLOs','Back-of-envelope Estimation'],
          resources:[
            {title:'System Design Basics',url:'https://www.youtube.com/@gkcs',type:'youtube',channel:'Gaurav Sen'},
          ]},
        { id:2, title:'Load Balancing & Caching', duration:'2–3 weeks',
          description:'Distribute traffic and cache responses to handle scale.',
          topics:['Load Balancer Types (L4, L7)','Consistent Hashing','CDN','Redis & Memcached','Cache Invalidation Strategies'],
          resources:[
            {title:'Caching Explained',url:'https://www.youtube.com/@gkcs',type:'youtube',channel:'Gaurav Sen'},
          ]},
        { id:3, title:'Database Design & Sharding', duration:'3–4 weeks',
          description:'Choose the right database and design it for scale.',
          topics:['SQL vs NoSQL Tradeoffs','Database Replication','Database Sharding','ACID vs BASE','Event Sourcing & CQRS'],
          resources:[
            {title:'Database System Design',url:'https://www.youtube.com/@gkcs',type:'youtube',channel:'Gaurav Sen'},
          ]},
        { id:4, title:'Microservices & Message Queues', duration:'3 weeks',
          description:'Decouple services and handle async workloads at scale.',
          topics:['Monolith vs Microservices','API Gateway','Service Discovery','Kafka Architecture','Pub/Sub Pattern','Circuit Breaker Pattern'],
          resources:[
            {title:'Kafka Explained',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
            {title:'Microservices Design',url:'https://www.youtube.com/@codeKarle',type:'youtube',channel:'codeKarle'},
          ]},
        { id:5, title:'Case Studies', duration:'3–4 weeks',
          description:'Practice designing real-world systems like Instagram, Netflix, Uber.',
          topics:['Design a URL Shortener','Design Instagram/Twitter','Design a Chat System','Design Netflix/YouTube','Design Uber/Food Delivery'],
          resources:[
            {title:'System Design Case Studies',url:'https://www.youtube.com/@codeKarle',type:'youtube',channel:'codeKarle'},
            {title:'System Design Primer',url:'https://github.com/donnemartin/system-design-primer',type:'docs'},
          ]},
      ]
    },
    {
      id: 'oop', title: 'Object Oriented Programming', icon: '🎯',
      description: 'Master OOP principles to write modular, reusable, and maintainable code.',
      color: '#0d9488', gradient: 'linear-gradient(135deg,#0d9488,#14b8a6)',
      duration: '2–3 months', difficulty: 'Beginner–Intermediate', tags: ['OOP','Design Patterns','SOLID'],
      steps: [
        { id:1, title:'Classes & Objects', duration:'1–2 weeks',
          description:'The fundamental building blocks of OOP.',
          topics:['Class Definition','Objects & Instantiation','Constructors & Destructors','Instance vs Class Variables','this/self Keyword'],
          resources:[
            {title:'OOP Tutorial',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'OOP in Java',url:'https://www.youtube.com/@programmingwithmosh',type:'youtube',channel:'Programming with Mosh'},
          ]},
        { id:2, title:'Encapsulation & Inheritance', duration:'2 weeks',
          description:'Protect your data and create hierarchies of classes.',
          topics:['Private, Public, Protected','Getters & Setters','Data Hiding','Single & Multiple Inheritance','super() keyword','Method Overriding','Abstract Classes & Interfaces'],
          resources:[
            {title:'Encapsulation & Inheritance',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
          ]},
        { id:3, title:'Polymorphism & Abstraction', duration:'2 weeks',
          description:'One interface, multiple implementations.',
          topics:['Method Overloading (Compile-time)','Method Overriding (Runtime)','Abstract Classes','Interfaces','Duck Typing (Python)','Virtual Functions (C++)'],
          resources:[
            {title:'Polymorphism Tutorial',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
          ]},
        { id:4, title:'Design Patterns & SOLID', duration:'3–4 weeks',
          description:'Proven solutions to common software design problems.',
          topics:['Creational Patterns (Singleton, Factory, Builder)','Structural Patterns (Adapter, Decorator, Facade)','Behavioral Patterns (Observer, Strategy, Command)','SOLID Principles'],
          resources:[
            {title:'Design Patterns',url:'https://www.youtube.com/@christopher_okhravi',type:'youtube',channel:'Christopher Okhravi'},
            {title:'Refactoring Guru',url:'https://refactoring.guru/design-patterns',type:'docs'},
          ]},
      ]
    },
  ],

  years: [
    {
      id: 'year-1', title: '1st Year B.Tech', shortTitle: 'Year 1', icon: '🌱',
      description: 'Build the foundations of computer science with programming basics, mathematics, and problem-solving habits.',
      color: '#10b981', gradient: 'linear-gradient(135deg,#10b981,#34d399)',
      subjects: ['C/C++ Language', 'Python', 'Engineering Mathematics'],
      duration: '1 Academic Year', difficulty: 'Beginner', tags: ['C/C++','Python','Maths'],
      steps: [
        { id:1, title:'C Programming Language', duration:'2–3 months',
          description:'C is the mother of programming languages. Learning it builds deep understanding of how computers work at low level.',
          topics:['Data Types & Variables','Control Flow (if/else, loops)','Functions & Recursion','Arrays & Strings','Pointers & Memory','Structures & Unions','File Handling'],
          resources:[
            {title:'C Programming Full Course',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'C by Jenny\'s Lectures',url:'https://www.youtube.com/@JennyslecturesCSIT',type:'youtube',channel:'Jenny\'s Lectures'},
            {title:'Learn C - GeeksforGeeks',url:'https://www.geeksforgeeks.org/c-programming-language/',type:'docs'},
          ]},
        { id:2, title:'C++ & OOP Basics', duration:'1–2 months',
          description:'Extend C with object-oriented programming. C++ is widely used in competitive programming and systems.',
          topics:['Classes & Objects','Constructors & Destructors','Inheritance & Polymorphism','STL Basics (vector, map, set)','Templates'],
          resources:[
            {title:'C++ Full Course',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'C++ Tutorial',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
          ]},
        { id:3, title:'Python Programming', duration:'1–2 months',
          description:'Python is the easiest language to learn and the most versatile. Perfect for beginners.',
          topics:['Python Basics & Syntax','Lists, Dictionaries, Tuples','Functions & Modules','File Handling','Introduction to OOP in Python'],
          resources:[
            {title:'Python Tutorial (Hindi)',url:'https://www.youtube.com/@CodeWithHarry',type:'youtube',channel:'CodeWithHarry'},
            {title:'Python Tutorial',url:'https://www.youtube.com/@sentdex',type:'youtube',channel:'sentdex'},
          ]},
        { id:4, title:'Engineering Mathematics', duration:'Throughout Year',
          description:'Math is the foundation of CS. Focus on the topics most relevant to computing.',
          topics:['Discrete Mathematics (Logic, Sets, Relations)','Linear Algebra (Matrices, Determinants)','Calculus (Limits, Derivatives, Integration)','Probability & Statistics Basics'],
          resources:[
            {title:'Engineering Maths',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
            {title:'3Blue1Brown Maths',url:'https://www.youtube.com/@3blue1brown',type:'youtube',channel:'3Blue1Brown'},
            {title:'Khan Academy',url:'https://khanacademy.org',type:'docs'},
          ]},
        { id:5, title:'Start Competitive Coding', duration:'Ongoing',
          description:'Begin solving easy problems to develop problem-solving habits early.',
          topics:['HackerRank Easy Problems','Basic Math Problems','String Manipulation','Array Problems','Simple Sorting'],
          resources:[
            {title:'HackerRank',url:'https://hackerrank.com/domains/cpp',type:'practice'},
            {title:'LeetCode Easy',url:'https://leetcode.com/problemset/?difficulty=EASY',type:'practice'},
          ]},
      ]
    },
    {
      id: 'year-2', title: '2nd Year B.Tech', shortTitle: 'Year 2', icon: '📚',
      description: 'Build core CS knowledge with the most important subjects — DSA, OOP, OS, DBMS, and Computer Networks.',
      color: '#3b82f6', gradient: 'linear-gradient(135deg,#3b82f6,#6366f1)',
      subjects: ['Java', 'DSA', 'OOP', 'DBMS', 'OS', 'Computer Networks'],
      duration: '1 Academic Year', difficulty: 'Intermediate', tags: ['Java','DSA','CS Core'],
      steps: [
        { id:1, title:'Java Programming', duration:'2 months',
          description:'Java is the industry-standard OOP language. Master it for backend and Android development.',
          topics:['Java Syntax & OOP','Collections Framework','Exception Handling','Java 8 Streams & Lambdas','Multithreading Basics'],
          resources:[
            {title:'Java Full Course',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'Java Tutorial',url:'https://www.youtube.com/@Telusko',type:'youtube',channel:'Telusko'},
          ]},
        { id:2, title:'Data Structures & Algorithms', duration:'4–5 months',
          description:'DSA is the most critical subject for placements and competitive programming. Start early and practice daily.',
          topics:['Arrays, Linked Lists, Stacks, Queues','Trees & Graphs','Sorting & Searching','Dynamic Programming','Greedy Algorithms'],
          resources:[
            {title:'DSA Full Course',url:'https://www.youtube.com/@takeUforward',type:'youtube',channel:'Striver'},
            {title:'DSA in Java',url:'https://www.youtube.com/@ApnaCollegeOfficial',type:'youtube',channel:'Apna College'},
            {title:'LeetCode',url:'https://leetcode.com',type:'practice'},
          ]},
        { id:3, title:'Object-Oriented Programming', duration:'1 month',
          description:'Deep-dive into OOP principles with Java or C++.',
          topics:['Encapsulation, Inheritance, Polymorphism','Abstract Classes & Interfaces','Design Patterns','SOLID Principles'],
          resources:[
            {title:'OOP in Java',url:'https://www.youtube.com/@programmingwithmosh',type:'youtube',channel:'Programming with Mosh'},
          ]},
        { id:4, title:'Database Management System', duration:'1–2 months',
          description:'Understand relational databases, SQL, and normalization.',
          topics:['ER Diagrams & Schema Design','SQL (DDL, DML, DCL)','Joins, Views, Triggers','Normalization','ACID Properties'],
          resources:[
            {title:'DBMS Full Course',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
            {title:'SQL Tutorial',url:'https://www.youtube.com/@techTFQ',type:'youtube',channel:'techTFQ'},
          ]},
        { id:5, title:'Operating Systems', duration:'1–2 months',
          description:'Study process management, memory, and file systems.',
          topics:['Processes & Threads','CPU Scheduling','Memory Management','Deadlocks','File Systems'],
          resources:[
            {title:'OS Full Course',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
            {title:'OS Playlist',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
          ]},
        { id:6, title:'Computer Networks', duration:'1–2 months',
          description:'Learn the OSI model, TCP/IP, and how the internet works.',
          topics:['OSI & TCP/IP Model','Data Link & Network Layer','TCP/UDP','Application Layer (HTTP, DNS)','Network Security Basics'],
          resources:[
            {title:'CN Full Course',url:'https://www.youtube.com/@nesoacademy',type:'youtube',channel:'Neso Academy'},
            {title:'CN Series',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
      ]
    },
    {
      id: 'year-3', title: '3rd Year B.Tech', shortTitle: 'Year 3', icon: '🚀',
      description: 'Specialize in AI, ML, and Data Science — the hottest fields. Build projects and aim for internships.',
      color: '#8b5cf6', gradient: 'linear-gradient(135deg,#8b5cf6,#ec4899)',
      subjects: ['AI', 'ML', 'Data Science'],
      duration: '1 Academic Year', difficulty: 'Intermediate–Advanced', tags: ['AI/ML','Internships','Specialization'],
      steps: [
        { id:1, title:'Artificial Intelligence', duration:'3–4 months',
          description:'Learn AI concepts from search algorithms to knowledge representation and planning.',
          topics:['Search Algorithms (A*, Minimax)','Knowledge Representation','Expert Systems','Game Theory','Planning & Reasoning'],
          resources:[
            {title:'AI Full Course',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
            {title:'MIT AI Course',url:'https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/',type:'docs'},
          ]},
        { id:2, title:'Machine Learning', duration:'4–5 months',
          description:'Learn to build models that learn from data — the core of modern AI.',
          topics:['Math (Linear Algebra, Stats)','Supervised & Unsupervised Learning','Model Evaluation','Feature Engineering','Deep Learning Intro'],
          resources:[
            {title:'ML Playlist',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Fast.ai',url:'https://course.fast.ai',type:'docs'},
          ]},
        { id:3, title:'Data Science', duration:'3–4 months',
          description:'Combine Python, stats, and ML to extract insights from real-world datasets.',
          topics:['EDA & Data Cleaning','Data Visualization','Statistical Analysis','End-to-End DS Projects','Kaggle Competitions'],
          resources:[
            {title:'Data Science Bootcamp',url:'https://www.youtube.com/@krishnaik06',type:'youtube',channel:'Krish Naik'},
            {title:'Kaggle Learn',url:'https://kaggle.com/learn',type:'docs'},
          ]},
        { id:4, title:'Internship Preparation', duration:'2–3 months',
          description:'Prepare for internship interviews with DSA practice and project building.',
          topics:['LeetCode Medium Problems','System Design Basics','Build 1–2 Projects','Resume Building','LinkedIn Optimization'],
          resources:[
            {title:'LeetCode',url:'https://leetcode.com',type:'practice'},
            {title:'Striver SDE Sheet',url:'https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/',type:'docs'},
          ]},
        { id:5, title:'Choose a Specialization', duration:'Ongoing',
          description:'Pick your career track and go deep into it.',
          topics:['Full Stack Development','AI/ML Engineering','DevOps & Cloud','Android Development','Cybersecurity'],
          resources:[
            {title:'Roadmap.sh',url:'https://roadmap.sh',type:'docs'},
          ]},
      ]
    },
    {
      id: 'year-4', title: '4th Year B.Tech', shortTitle: 'Year 4', icon: '🎓',
      description: 'Final year — focus on System Design, capstone projects, placement prep, and Cloud Computing.',
      color: '#f59e0b', gradient: 'linear-gradient(135deg,#f59e0b,#ef4444)',
      subjects: ['System Design', 'Project Ideas', 'Software Engineering', 'Cloud Computing'],
      duration: '1 Academic Year', difficulty: 'Advanced', tags: ['Placements','System Design','Cloud'],
      steps: [
        { id:1, title:'System Design', duration:'2–3 months',
          description:'System Design is asked in senior SDE interviews. Learn to design large-scale systems.',
          topics:['Scalability & CAP Theorem','Load Balancing, Caching','Database Design & Sharding','Microservices & API Design','Case Studies (Instagram, Netflix, Uber)'],
          resources:[
            {title:'System Design Playlist',url:'https://www.youtube.com/@gkcs',type:'youtube',channel:'Gaurav Sen'},
            {title:'System Design Primer',url:'https://github.com/donnemartin/system-design-primer',type:'docs'},
          ]},
        { id:2, title:'Final Year Capstone Project', duration:'6 months',
          description:'Build a production-quality project that showcases all your skills.',
          topics:['Pick a Problem Statement','Use Modern Tech Stack','Write Technical Documentation','Deploy & Host','Present & Demo','Publish on GitHub'],
          resources:[
            {title:'Project Ideas',url:'https://www.youtube.com/@TraversyMedia',type:'youtube',channel:'Traversy Media'},
            {title:'GitHub Student Pack',url:'https://education.github.com/pack',type:'docs'},
          ]},
        { id:3, title:'Software Engineering Principles', duration:'1–2 months',
          description:'Learn industry-level software development practices.',
          topics:['Software Development Life Cycle','Agile & Scrum','CI/CD Pipelines','Testing (Unit, Integration, E2E)','Code Reviews & Git Workflow'],
          resources:[
            {title:'Software Engineering',url:'https://www.youtube.com/@GateSmashers',type:'youtube',channel:'Gate Smashers'},
          ]},
        { id:4, title:'Cloud Computing', duration:'2–3 months',
          description:'Learn cloud platforms to build, deploy, and scale applications in the cloud.',
          topics:['Cloud Basics (IaaS, PaaS, SaaS)','AWS / GCP / Azure Fundamentals','EC2, S3, Lambda, RDS','Docker & Kubernetes','Serverless Architecture'],
          resources:[
            {title:'AWS for Beginners',url:'https://www.youtube.com/@NetworkChuck',type:'youtube',channel:'NetworkChuck'},
            {title:'Cloud Computing',url:'https://www.youtube.com/@TechWorldwithNana',type:'youtube',channel:'TechWorld with Nana'},
            {title:'AWS Free Tier',url:'https://aws.amazon.com/free/',type:'docs'},
          ]},
        { id:5, title:'Placement Preparation', duration:'3–4 months',
          description:'Final push for campus placements — crack your dream company!',
          topics:['LeetCode Hard Problems','Mock Interviews','System Design Practice','HR & Behavioral Rounds','Offer Negotiation'],
          resources:[
            {title:'LeetCode',url:'https://leetcode.com',type:'practice'},
            {title:'Striver SDE Sheet',url:'https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/',type:'docs'},
            {title:'NeetCode',url:'https://neetcode.io',type:'practice'},
          ]},
      ]
    },
  ]
};
